apiVersion: v1
kind: Namespace
metadata:
  name: redis-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: redis-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: redis
  resources:
    requests:
      storage: 10Gi

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis
  namespace: redis-system
  labels:
    app: redis
data:
  redis.conf: |-
    requirepass root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis-system
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis
        - name: redis-config
          configMap:
            name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-system
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30002
    protocol: TCP
  selector:
    app: redis
