apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-system
spec:
  type: LoadBalancer
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis-app
