apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: redis-system
  labels:
    app: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config
