apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-system
spec:
  type: LoadBalancer
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql-app
