apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb-system
spec:
  type: LoadBalancer
  ports:
  - name: mongodb-port
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb-app
