apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-app
  namespace: mongodb-system
  labels:
    app: mongodb-app
spec:
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mongodb-pvc
              mountPath: /data/db
      volumes:
        - name: mongodb-pvc
          persistentVolumeClaim:
            claimName: mongodb-pvc
