apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: mongodb-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mongodb
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb-system
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-system
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30000
    protocol: TCP
  selector:
    app: mongodb
