apiVersion: v1
kind: Namespace
metadata:
  name: mysql-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: mysql-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mysql
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql-system
data:
  mysqld.cnf: |
    [mysqld]
    lower_case_table_names=1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-system
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          args:
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: dbport
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql
        - name: mysql-config
          configMap:
            name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-system
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30001
    protocol: TCP
  selector:
    app: mysql
