version: '3.9'
services:
  mysql:
    image: mysql
    command: 
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongodb/db:/data/db
      - ./data/mongodb/configdb:/data/configdb
    ports:
      - "27017:27017"
  redis:
    image: redis
    volumes:
      - ./config/redis:/usr/local/etc/redis
      - ./data/redis:/data
    ports:
      - "6379:6379"
