version: '3.9'
services:
  redis-master:
    image: redis
    volumes:
      - ./config/redis-master:/usr/local/etc/redis
      - ./data/redis-master:/data
    ports:
      - "6380:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-slave-1:
    image: redis
    volumes:
      - ./config/redis-slave-1:/usr/local/etc/redis
      - ./data/redis-slave-1:/data
    ports:
      - "6381:6379"
    links:
      - redis-master
    depends_on:
      - redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-slave-2:
    image: redis
    volumes:
      - ./config/redis-slave-2:/usr/local/etc/redis
      - ./data/redis-slave-2:/data
    ports:
      - "6382:6379"
    links:
      - redis-master
    depends_on:
      - redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
